apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ingress-nagp-ecom-ui
  labels:
    app: nagp-ecom-ui
    type: gateway-ingress
    stack: nagp-ecom
spec:
  parentRefs:
    - name: traefik-gateway # Name of the Gateway that Traefik creates when you enable the Gateway API provider
      namespace: traefik
  hostnames:
    - "ecom.docker.localhost"
  rules:
  - name: ui-routes
    matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nagp-ecom-ui
      port: 80