apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-ecom-identity-api
  labels:
    app: nagp-ecom-identity-api
    type: api
    stack: nagp-ecom-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp-ecom-identity-api
      stack: nagp-ecom-api
  template:
    metadata:
      labels:
        app: nagp-ecom-identity-api
        type: api
        stack: nagp-ecom-api
    spec:
      containers:
        - name: nagp-ecom-identity-api
          image: nagp-ecom-identity-api
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_USERNAME
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=ecomdb;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD)"
            - name: OpenIddict__Clients__EcomApi__ClientId
              valueFrom:
                secretKeyRef:
                  name: identity-api-secrets
                  key: ECOMAPI_CLIENT_ID
            - name: OpenIddict__Clients__EcomApi__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: identity-api-secrets
                  key: ECOMAPI_CLIENT_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
