apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-api-secrets
  namespace: nagp-ecom
spec:
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  data:
    - secretKey: ECOMAPI_CLIENT_SECRET
      remoteRef:
        key: secret/ECOMAPI-CLIENT-SECRET
    - secretKey: OPENIDDICT_SIGNING_CERT_PFX
      remoteRef:
        key: secret/OPENIDDICT-SIGNING-CERT-PFX
    - secretKey: OPENIDDICT_SIGNING_CERT_PASSWORD
      remoteRef:
        key: secret/OPENIDDICT-SIGNING-CERT-PASSWORD
    - secretKey: OPENIDDICT_ENCRYPTION_CERT_PFX
      remoteRef:
        key: secret/OPENIDDICT-ENCRYPTION-CERT-PFX
    - secretKey: OPENIDDICT_ENCRYPTION_CERT_PASSWORD
      remoteRef:
        key: secret/OPENIDDICT-ENCRYPTION-CERT-PASSWORD
  target:
    name: identity-api-secrets