<#
.SYNOPSIS
    Generates persistent OpenIddict signing and encryption X.509 certificates,
    then uploads them as base64-encoded secrets to Azure Key Vault.

.DESCRIPTION
    Run this ONCE per environment. The certs are self-signed with a 10-year validity.
    After upload to AKV, the Identity API pods will pick them up via ExternalSecret
    on next restart. Existing tokens remain valid as long as the same certs are used.

.PARAMETER VaultName
    Azure Key Vault name. Default: kv-nagp-ecom-secrets

.PARAMETER OutputDir
    Local directory for the PFX files. Defaults to .certs\ in the repo root (next to this script).
    The folder is gitignored. Use this same path if you need to re-upload to AKV.

.EXAMPLE
    # From repo root (src/):
    .\generate-openiddict-certs.ps1
    .\generate-openiddict-certs.ps1 -VaultName my-other-keyvault
#>
param(
    [string]$VaultName = "kv-nagp-ecom-secrets",
    [string]$OutputDir = (Join-Path $PSScriptRoot ".certs")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Ensure output directory exists ──────────────────────────────────────────
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

# ── Generate a random PFX password ──────────────────────────────────────────
function New-RandomPassword([int]$Length = 32) {
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    -join (1..$Length | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
}

# ── Ensure a PFX exists (reuse if already generated by Aspire AppHost) ──────
# The password file sits next to the PFX so both can be loaded independently.
function EnsureCert {
    param([string]$PfxPath, [string]$PasswordPath, [string]$Subject)

    if (Test-Path $PfxPath) {
        Write-Host "  Reusing existing cert: $PfxPath"
    } else {
        Write-Host "  Generating cert: $PfxPath"
        $pw = New-RandomPassword
        Set-Content -Path $PasswordPath -Value $pw -NoNewline

        $securePassword = ConvertTo-SecureString $pw -AsPlainText -Force
        $cert = New-SelfSignedCertificate `
            -Subject $Subject `
            -CertStoreLocation "Cert:\CurrentUser\My" `
            -KeyUsage DigitalSignature, KeyEncipherment `
            -KeyAlgorithm RSA `
            -KeyLength 2048 `
            -NotAfter (Get-Date).AddYears(10) `
            -FriendlyName $Subject
        Export-PfxCertificate -Cert $cert -FilePath $PfxPath -Password $securePassword | Out-Null
        Remove-Item "Cert:\CurrentUser\My\$($cert.Thumbprint)" -Force
    }

    $password = Get-Content -Path $PasswordPath -Raw
    $base64 = [System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes($PfxPath))
    return @{ Base64 = $base64; Password = $password }
}

# ── Signing certificate ──────────────────────────────────────────────────────
Write-Host "Signing certificate:"
$signing = EnsureCert `
    -PfxPath      (Join-Path $OutputDir "signing.pfx") `
    -PasswordPath (Join-Path $OutputDir "signing.password") `
    -Subject      "CN=OpenIddict Signing"

# ── Encryption certificate ───────────────────────────────────────────────────
Write-Host "Encryption certificate:"
$encryption = EnsureCert `
    -PfxPath      (Join-Path $OutputDir "encryption.pfx") `
    -PasswordPath (Join-Path $OutputDir "encryption.password") `
    -Subject      "CN=OpenIddict Encryption"

# ── Upload to Azure Key Vault ────────────────────────────────────────────────
Write-Host ""
Write-Host "Uploading secrets to Azure Key Vault '$VaultName'..."

# Write values to temp files and use --file to avoid:
#   1. Special-character escaping issues with --value on Windows
#   2. Command-line length limits for large base64 PFX strings
$secrets = [ordered]@{
    "OPENIDDICT-SIGNING-CERT-PFX"         = $signing.Base64
    "OPENIDDICT-SIGNING-CERT-PASSWORD"    = $signing.Password
    "OPENIDDICT-ENCRYPTION-CERT-PFX"      = $encryption.Base64
    "OPENIDDICT-ENCRYPTION-CERT-PASSWORD" = $encryption.Password
}

$tmpFile = [System.IO.Path]::GetTempFileName()
try {
    foreach ($key in $secrets.Keys) {
        Write-Host "  Setting secret: $key"
        [System.IO.File]::WriteAllText($tmpFile, $secrets[$key], [System.Text.UTF8Encoding]::new($false))
        az keyvault secret set --vault-name $VaultName --name $key --file $tmpFile --output none
        if ($LASTEXITCODE -ne 0) {
            throw "az keyvault secret set failed for '$key' (exit code $LASTEXITCODE)"
        }
    }
} finally {
    Remove-Item $tmpFile -Force -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "Done. Secrets uploaded to AKV. The ExternalSecret controller will sync them"
Write-Host "to the 'identity-api-secrets' K8s Secret on next reconciliation (~1 min)."
Write-Host ""
Write-Host "Certs are stored at: $OutputDir (gitignored)"
Write-Host "Aspire AppHost reads from the same folder — K8s and local use identical cert material."
