apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: src

build:
  artifacts:
    - image: ankurmathur01nagarro/nagp-ecom-ui
      context: ui
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ui/deployment/deployment.yaml
