apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-inventory-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventory-migration
  newTag: c9c5ab5635fac8d7aeb6315ee76fd2e2698d3ad2
- name: nagp-ecom-inventoryapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventoryapi
  newTag: c9c5ab5635fac8d7aeb6315ee76fd2e2698d3ad2
