apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-inventory-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventory-migration
  newTag: 3a9077a042cdff7ffd6eb268230bb040bd0e0e9f
- name: nagp-ecom-inventoryapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventoryapi
  newTag: 3a9077a042cdff7ffd6eb268230bb040bd0e0e9f
