apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-inventory-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventory-migration
  newTag: f06e793d45e205a38fe4d402a9c06bf394319cd6
- name: nagp-ecom-inventoryapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventoryapi
  newTag: f06e793d45e205a38fe4d402a9c06bf394319cd6
