apiVersion: v1
kind: Service
metadata:
  name: nagp-ecom-productapi
  labels:
    app: nagp-ecom-productapi
    type: api
    stack: nagp-ecom-api
  namespace: nagp-ecom
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: svc-port-http
  selector:
    app: nagp-ecom-productapi
    stack: nagp-ecom-api
