apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: cloud

images:
- name: nagp-ecom-inventory-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventory-migration
  newTag: bab971bda92aac2f050fe0f8ac26f966afbf60a6
- name: nagp-ecom-inventoryapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventoryapi
  newTag: bab971bda92aac2f050fe0f8ac26f966afbf60a6
