apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  deployment.environment: cloud

images:
  - name: nagp-ecom-inventory-migration
    newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventory-migration
    newTag: 70b217fcd423a0f5419df9337f63746a843dd028
  - name: nagp-ecom-inventoryapi
    newName: docker.io/ankurmathur01nagarro/nagp-ecom-inventoryapi
    newTag: 70b217fcd423a0f5419df9337f63746a843dd028
