apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-migration
  newTag: 0efb45629a958a8f4a35f4b6e227567ed85f6d44
- name: nagp-ecom-webapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-webapi
  newTag: 0efb45629a958a8f4a35f4b6e227567ed85f6d44
