apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-migration
  newTag: 5b918d6110974484e19a045693bfaa4e0df0496d
- name: nagp-ecom-webapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-webapi
  newTag: 5b918d6110974484e19a045693bfaa4e0df0496d
