apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-migration
  newTag: 4cd73fd5ade385510f0828a51868103235732731
- name: nagp-ecom-webapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-webapi
  newTag: 4cd73fd5ade385510f0828a51868103235732731
