apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nagp-ecom
commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-identity-api
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-identity-api
  newTag: 886f7bd0aa9208be291d90cf14c0af38a147bf9d
