apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nagp-ecom
commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-identity-api
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-identity-api
  newTag: 0efb45629a958a8f4a35f4b6e227567ed85f6d44
