apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-identity-api
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-identity-api
  newTag: 8fd5d3a03435fc55539d2c15f887b525aa892916
