apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: cloud

patches:
- path: patch.pvc.product-images.cloud.yaml
- path: patch.deploy.no-local-storage.cloud.yaml

images:
- name: nagp-ecom-product-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-product-migration
  newTag: f06e793d45e205a38fe4d402a9c06bf394319cd6
- name: nagp-ecom-productapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-productapi
  newTag: f06e793d45e205a38fe4d402a9c06bf394319cd6
