apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-product-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-product-migration
  newTag: 3b84a8b919dd6f019bad105fbd3921ed92d85209
- name: nagp-ecom-productapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-productapi
  newTag: 3b84a8b919dd6f019bad105fbd3921ed92d85209
