apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-product-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-product-migration
  newTag: 676cb6714cd860afb3662b5e4ed5dd8e6ecd6e19
- name: nagp-ecom-productapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-productapi
  newTag: 676cb6714cd860afb3662b5e4ed5dd8e6ecd6e19
