apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonAnnotations:
  deployment.environment: local

images:
- name: nagp-ecom-product-migration
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-product-migration
  newTag: da10d0ad4ab2d8519b04a1857309a2b852f54e7f
- name: nagp-ecom-productapi
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-productapi
  newTag: da10d0ad4ab2d8519b04a1857309a2b852f54e7f
