apiVersion: v2
name: nagp-ecom
description: ArgoCD app-of-apps using official argocd-apps chart
type: application
version: 0.2.0
appVersion: "0.0.2"

dependencies:
  - name: argocd-apps
    version: "2.0.4"
    repository: https://argoproj.github.io/argo-helm