mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheusremotewrite:
      endpoint: 0.0.0.0:9090
  processors:
    batch:
      timeout: 5s
      send_batch_size: 1024
  exporters:
    debug:
      verbosity: detailed
    otlp_http/newrelic:
      endpoint: https://otlp.eu01.nr-data.net:4318
      tls:
        insecure: true
      headers:
        api-key: ${NEW_RELIC_API_KEY}
    otlp_grpc/jaeger:
      endpoint: jaeger.observability.svc.cluster.local:4317
      tls:
        insecure: true
    otlp_http/loki:
      endpoint: http://loki.observability.svc.cluster.local:3100/otlp
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [otlp, prometheusremotewrite]
        processors: [batch]
        exporters: [otlp_http/newrelic, debug]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp_http/loki, otlp_http/newrelic, debug]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp_grpc/jaeger, otlp_http/newrelic, debug]
extraEnvs:
  - name: NEW_RELIC_API_KEY
    valueFrom:
      secretKeyRef:
        name: newrelic-otel-secret
        key: api-key