apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: duckdns-credentials
  namespace: cert-manager
spec:
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: secret/DUCKDNS-TOKEN
  target:
    name: duckdns-credentials
