apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets-nagp
  namespace: nagp-ecom
spec:
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: secret/POSTGRES-USERNAME
    - secretKey: POSTGRES_PASSWORD 
      remoteRef:
        key: secret/POSTGRES-PASSWORD
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/GOOGLE-CLIENT-ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/GOOGLE-CLIENT-SECRET
  target:
    name: secrets-nagp