apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets-nagp
  namespace: nagp-ecom
spec:
  secretStoreRef:
    name: secrets-store
    kind: SecretStore
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: secret/POSTGRES-USERNAME
    - secretKey: POSTGRES_PASSWORD 
      remoteRef:
        key: secret/POSTGRES-PASSWORD
  target:
    name: secrets-nagp