apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secrets-store
  namespace: nagp-ecom
spec:
  provider:
    azurekv:
      tenantId: "31798997-cabb-4bb5-a83d-bc06837663e5"
      vaultUrl: "https://kv-nagp-ecom-secrets.vault.azure.net/"
      authSecretRef:
        clientId:
          name: secret-azure-sp
          key: ClientID
        clientSecret:
          name: secret-azure-sp
          key: ClientSecret