apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nagp-ecom

resources:
- ../../base

images:
- name: nagp-ecom-ui
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-ui
  newTag: 9642adfbf919b9736018b0b7e7f19b0c843f77a9
