apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nagp-ecom

resources:
- ../../base

images:
- name: nagp-ecom-ui
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-ui
  newTag: b4431984b9e8910dea83c8fc90a1231fe8e0522c
