apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nagp-ecom

resources:
- ../../base

images:
- name: nagp-ecom-ui
  newName: docker.io/ankurmathur01nagarro/nagp-ecom-ui
  newTag: 260a83eb103839279cee99d7c939f31fe3b346fe
