apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secretstore.hashicorp-vault.k8s.yaml
  - secret.postgres.k8s.yaml
  - secret.identity-api.k8s.yaml

namespace: nagp-ecom
commonAnnotations:
  deployment.environment: local

patches:
  - path: patch.statefulSet.database.k8s.yaml
