apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secrets-store
spec:
  provider:
    vault:
      version: "v2"
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      auth:
        tokenSecretRef:
          key: token
          name: vault-token