apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-api-secrets
  namespace: nagp-ecom
spec:
  secretStoreRef:
    name: secrets-store
    kind: SecretStore
  data:
    - secretKey: ECOMAPI_CLIENT_SECRET 
      remoteRef:
        key: secret/staging/identity-api
        property: ECOMAPI_CLIENT_SECRET
  target:
    name: identity-api-secrets