apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  deployment.environment: cloud

patches:
  - path: patch.deploy.no-local-storage.cloud.yaml
