apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-ecom-api
  labels:
    app: nagp-ecom-api
    type: api
    stack: nagp-ecom-api
  namespace: nagp-ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp-ecom-api
      stack: nagp-ecom-api
  template:
    metadata:
      labels:
        app: nagp-ecom-api
        type: api
        stack: nagp-ecom-api
    spec:
      initContainers:
        - name: migration
          image: nagp-ecom-migration
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=ecomdb;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD)"
      containers:
        - name: nagp-ecom-api
          image: nagp-ecom-webapi
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-nagp
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=ecomdb;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD)"
            - name: IdentityApi__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: identity-api-secrets
                  key: ECOMAPI_CLIENT_SECRET
            - name: OpenIddict__Issuer
              valueFrom:
                configMapKeyRef:
                  name: identity-api-config
                  key: HOSTNAME
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
