apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-api-secrets
  namespace: nagp-ecom
spec:
  secretStoreRef:
    name: secrets-store
    kind: ClusterSecretStore
  data:
    - secretKey: ECOMAPI_CLIENT_SECRET 
      remoteRef:
        key: secret/ECOMAPI-CLIENT-SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: secret/GOOGLE-CLIENT-ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: secret/GOOGLE-CLIENT-SECRET
  target:
    name: web-api-secrets