apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nagp-ecom

resources:
  - httproute.api.k8s.yaml
  - httproute.identity-api.k8s.yaml
  - statefulSet.database.k8s.yaml
  - pvc.postgres.k8s.yaml
  - service.database.k8s.yaml
  - deploy.webapi.k8s.yaml
  - service.webapi.k8s.yaml
  - deploy.identity-api.k8s.yaml
  - service.identity-api.k8s.yaml

configMapGenerator:
  - name: vault-token
    namespace: default
    options:
      disableNameSuffixHash: true
    literals:
      - token=root