apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-iscsi.yaml
  - secret-nfs.yaml

helmCharts:
  # iSCSI driver → sc-block
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    version: 0.14.6
    releaseName: democratic-csi-iscsi
    namespace: democratic-csi
    valuesFile: values-iscsi.yaml

  # NFS driver → sc-shared
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    version: 0.14.6
    releaseName: democratic-csi-nfs
    namespace: democratic-csi
    valuesFile: values-nfs.yaml