apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-iscsi-config
  namespace: democratic-csi
stringData:
  driver-config-file.yaml: |
    driver: freenas-api-iscsi
    httpConnection:
      protocol: http
      host: 192.168.1.18
      port: 80
      apiKey: "1-HVrFUnEKZfmmEafZq5p5k247BLGcqfe2BvF1rQESYkSJDn8GoK7ASthjYtxtC9JX"
      allowInsecure: true
    zfs:
      datasetParentName: pool1/pool1-iscsi
      detachedSnapshotsDatasetParentName: pool1/pool1-iscsi-snapshots
      datasetEnableQuotas: true
      datasetPermissionsMode: "0777"
    iscsi:
      targetPortal: "192.168.1.18:3260"
      namePrefix: "csi-"
      nameSuffix: "-k3s"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
      extentInsecureTpc: true
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"