apiVersion: v1
kind: Secret
metadata:
  name: democratic-csi-nfs-config
  namespace: democratic-csi
stringData:
  driver-config-file.yaml: |
    driver: freenas-api-nfs
    httpConnection:
      protocol: http
      host: 192.168.1.18
      port: 80
      apiKey: "1-HVrFUnEKZfmmEafZq5p5k247BLGcqfe2BvF1rQESYkSJDn8GoK7ASthjYtxtC9JX"
      allowInsecure: true
    zfs:
      datasetParentName: pool1/k8s-nfs
      detachedSnapshotsDatasetParentName: pool1/k8s-nfs-snapshots
      datasetEnableQuotas: true
      datasetPermissionsMode: "0777"
    nfs:
      shareHost: 192.168.1.18
      shareAllowedNetworks:
        - "192.168.1.0/24"
      shareMaprootUser: root
      shareMaprootGroup: root