csiDriver:
  name: org.democratic-csi.iscsi

driver:
  existingConfigSecret: democratic-csi-iscsi-config

node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /etc/iscsi
    iscsiDirHostPathType: ""

storageClasses: []

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
    cpu: 20m