steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/nagp-ecom-ui:latest .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/nagp-ecom-ui:latest']
   secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/docker-password/versions/1
      env: 'PASSWORD'
    - versionName: projects/$PROJECT_NUMBER/secrets/docker-username/versions/1
      env: 'USERNAME'
