apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/managed-by: git
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/track: "true"

configMapGenerator:
  - name: alloy
    files:
      - config.alloy
