apiVersion: install.istio.io/v1alpha3
kind: IstioOperator
metadata:
  name: istio-controlplane
  namespace: istio-system
spec:
  profile: ambient
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
  values:
    cni:
      excludeNamespaces:
        - kube-system
        - istio-system     # ← prevents ambient capturing system pods
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing: {} # disable legacy MeshConfig tracing options
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"   # ← required for ztunnel HBONE tunneling
    extensionProviders:
    - name: otel
      opentelemetry:
        service: alloy.observability.svc.cluster.local
        port: 4317
        resource_detectors:
          environment: {}
    accessLogFile: /dev/stdout
