FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /App

COPY . .
RUN dotnet restore ./ECOM.InventoryApi.MigrationJob/ECOM.InventoryApi.MigrationJob.csproj
RUN dotnet publish ./ECOM.InventoryApi.MigrationJob/ECOM.InventoryApi.MigrationJob.csproj -o out

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /App
COPY --from=build /App/out .

ENTRYPOINT ["dotnet", "ECOM.InventoryApi.MigrationJob.dll"]
