FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /App

COPY . .
RUN dotnet restore ./ECOM.ProductApi/ECOM.ProductApi.csproj
RUN dotnet publish ./ECOM.ProductApi/ECOM.ProductApi.csproj -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /App
COPY --from=build /App/out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "ECOM.ProductApi.dll"]
