apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  deployment.environment: cloud

images:
  - name: nagp-ecom-migration
    newName: docker.io/ankurmathur01nagarro/nagp-ecom-migration
    newTag: 0.0.2
  - name: nagp-ecom-webapi
    newName: docker.io/ankurmathur01nagarro/nagp-ecom-webapi
    newTag: 0.0.2